### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by tony-kerz** [Capgemini/dcos-cli-docker#1]
hi,

thanks for the cool image, this is just what i was looking for.

i'm having an issue where i run like:

```
docker run -it -e MESOS_MASTER_URL=http://my.marathon.url -e MARATHON_URL=http://my.marathon.url -e TOKEN=mytoken -e EMAIL=anthony.kerz@gmail.com capgemini/dcos-cli marathon app list
```

and i get:

```
Updating source [https://github.com/mesosphere/multiverse/archive/master.zip]
Updating source [https://github.com/mesosphere/universe/archive/version-1.x.zip]
Traceback (most recent call last):
  File "/dcos-cli/bin/dcos-marathon", line 11, in <module>
    sys.exit(main())
  File "/dcos-cli/lib/python2.7/site-packages/dcoscli/marathon/main.py", line 115, in main
    return _main()
  File "/dcos-cli/lib/python2.7/site-packages/dcoscli/marathon/main.py", line 128, in _main
    return cmds.execute(_cmds(), args)
  File "/dcos-cli/lib/python2.7/site-packages/dcos/cmds.py", line 43, in execute
    return function(*params)
  File "/dcos-cli/lib/python2.7/site-packages/dcoscli/marathon/main.py", line 360, in _list
    client = marathon.create_client()
  File "/dcos-cli/lib/python2.7/site-packages/dcos/marathon.py", line 27, in create_client
    return Client(marathon_url)
  File "/dcos-cli/lib/python2.7/site-packages/dcos/marathon.py", line 83, in __init__
    version = LooseVersion(self.get_about()["version"])
  File "/dcos-cli/lib/python2.7/site-packages/dcos/marathon.py", line 119, in get_about
    response = http.get(url, to_exception=_to_exception)
  File "/dcos-cli/lib/python2.7/site-packages/dcos/http.py", line 125, in get
    return request('get', url, to_exception=to_exception, **kwargs)
  File "/dcos-cli/lib/python2.7/site-packages/dcos/util.py", line 448, in timer
    return fn(*args, **kwargs)
  File "/dcos-cli/lib/python2.7/site-packages/dcos/http.py", line 97, in request
    raise to_exception(response)
  File "/dcos-cli/lib/python2.7/site-packages/dcos/marathon.py", line 57, in _to_exception
    message = response.json().get('message')
  File "/dcos-cli/lib/python2.7/site-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

any idea what i'm doing wrong?

regards,
tony.

**Comment by tony-kerz** [comment]
turns out it was an issue with `MARATHON_URL` needing to be specified with port 8080 (at least in my case, i'm guessing that is a default port, but could probably be changed).

so the following works ok:

```
docker run -it -e MESOS_MASTER_URL=http://my.marathon.url -e MARATHON_URL=http://my.marathon.url:8080 -e TOKEN=mytoken -e EMAIL=anthony.kerz@gmail.com capgemini/dcos-cli marathon app list
```

one thing that threw me being green to dcos/mesos/marathon, was that another person installed dcos and used 'marathon' in the 'mesos master' host name (e.g. `my.marathon.url`), which confused me around distinguishing between `MESOS_MASTER_URL` and `MARATHON_URL`.

but better now, just leaving this here in case it helps someone else.

**Comment by enxebre** [comment]
cool, don't hesitate to open new tickets if you find any trouble.
Thanks!
